version: '1.0'
networks:
  roboshop:
   driver: bridge
volumes:
  mysql:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: /home/ec2-user/mysql
services:
  web:
   image: web:v1
   container_name: web
   depends_on: 
   - catalogue
   - user
   - cart
   - shipping
   - payment
   - ratings
   ports: 
   - 80:80
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  redis:
    image: redis
  cart: 
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql: 
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql: /var/lib/mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment: 
    image: payment:v1
    container_name: payment
    depends_on: 
    - rabbitmq
  ratings:
    image: ratings:v1
    container_name: ratings
    depends_on:
    - mysql

